import { Request, Response } from "express";
import ApiResponse from "../utils/apiResponse.js";

// github issue creation via webhook to n8n
export const createIssue = async (req: Request, res: Response) => {
  try {
    const {
      title,
      description,
      issue_type,
      severity,
      merchant_id,
      ticket_id,
      error_code,
      reproduction_steps,
      expected_behavior,
      actual_behavior,
    } = req.body;

    if (!title || !description) {
      return ApiResponse.error(res, "Title and description are required", 400);
    }

    console.log("[GitHub] Creating issue:", { title, issue_type, severity });

    // build issue body
    const issueBody = `
## Issue Summary
${description}

## Details
- **Issue Type**: ${issue_type || "bug"}
- **Severity**: ${severity || "medium"}
- **Merchant ID**: ${merchant_id || "N/A"}
- **Related Ticket**: ${ticket_id || "N/A"}
- **Error Code**: ${error_code || "N/A"}

## Reproduction Steps
${reproduction_steps || "Not provided"}

## Expected Behavior
${expected_behavior || "Not provided"}

## Actual Behavior
${actual_behavior || "Not provided"}

---
*Auto-generated by HealAgent Support System*
*Timestamp: ${new Date().toISOString()}*
    `.trim();

    // determine labels based on issue type and severity
    const labels: string[] = [];
    if (issue_type) labels.push(issue_type);
    if (severity) labels.push(`priority:${severity}`);
    labels.push("auto-generated");

    // payload for n8n webhook
    const webhookPayload = {
      action: "create_issue",
      title,
      body: issueBody,
      labels,
      metadata: {
        merchant_id,
        ticket_id,
        error_code,
        severity,
        issue_type,
        created_at: new Date().toISOString(),
      },
    };

    // github issue is handled by n8n agent directly
    // this endpoint just logs and confirms the request
    console.log("[GitHub] Issue request received:", webhookPayload);

    return ApiResponse.success(res, {
      message: "GitHub issue creation request received",
      issue: {
        title,
        labels,
        status: "queued",
        metadata: webhookPayload.metadata,
      },
    });
  } catch (error) {
    console.error("[GitHub] Error creating issue:", error);
    return ApiResponse.error(res, "Failed to create GitHub issue", 500);
  }
};

// get issue status (for tracking)
export const getIssueStatus = async (req: Request, res: Response) => {
  try {
    const { issueId } = req.params;

    // this would typically query github api or a local cache
    // for now, return a mock status
    return ApiResponse.success(res, {
      issue_id: issueId,
      status: "open",
      message: "Issue tracking not fully implemented",
    });
  } catch (error) {
    console.error("[GitHub] Error getting issue status:", error);
    return ApiResponse.error(res, "Failed to get issue status", 500);
  }
};
